{% set name = "xtensor-blas" %}
{% set version = "0.19.2" %}
{% set sha256 = "ef678c0e3f581cc8d61ea002c904c76513c8b0f798f9c9acaf980a835f9d09aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor-blas/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - xtensor >=0.23.0,<0.24.0
  run:
    - {{ pin_compatible('xtensor', max_pin='x.x') }}
    - blas-devel

test:
  commands:
    - test -f ${PREFIX}/include/xtensor-blas/xblas.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor-blas\xblas.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blas\xtensor-blasConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blas\xtensor-blasConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor-blas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BLAS extension to xtensor
  description: xtensor-blas is an extension to the xtensor library, offering bindings to BLAS and LAPACK libraries through cxxblas and cxxlapack from the FLENS project.
  doc_url: https://xtensor-blas.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor-blas

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
