{% set name = "xtensor-blas" %}
{% set version = "0.13.1" %}
{% set sha256 = "3798fedc0def008662d2c99948b35ff01d6a86deffb6245b80fd37745c6c37d5" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-blas/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  # Skipping blas on windows since openblas is not available.
  # cf. https://github.com/conda-forge/openblas-feedstock/issues/2
  features:                     # [not win]
    - blas_{{ variant }}        # [not win]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - xtensor >=0.17.0,<0.18.0
    - blas 1.1 {{ variant }}    # [not win]
    - openblas                  # [not win]
  run:
    - xtensor >=0.17.0,<0.18.0
    - blas 1.1 {{ variant }}    # [not win]
    - openblas                  # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/xtensor-blas/xblas.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-blas/xtensor-blasConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-blas\xblas.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blasConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-blasConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'BLAS extension to xtensor'
  description: 'xtensor-blas is an extension to the xtensor library, offering bindings to BLAS and LAPACK libraries through cxxblas and cxxlapack from the FLENS project.'
  doc_url: http://xtensor-blas.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-blas

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
