travis:
  secure:
    BINSTAR_TOKEN: Hzmm6g1oZTLFOJURfBbwMzJh48/alavK9/XwS7ymEpQKYyOKwqjiWuFn7Y1Aa/9D96HMbg+rZQI7hT5Fwc6rab494oOUaG5J0L/IYbkoPfBRfSul1dSq2Kgnv6ogTG7wj/PgKNhqAJEwMht3tB7J0qo+CoJ4vLDTvvxJ9jMZm7vK8YqnUIqj5HKD80fNK7ljvLO6RUOCiPingolNLYtuMwgow086//J9SzLaP0YViN5qzh9NMuoZnd/r+F/68XWLnXiSgifA/dnQRtoMCCnOB4MSYa71MMaojoW4d/u7nbT5npEChNqy4yAfbAMIXZT0kLQ1vQm7iSBZ24/T77Vm+BVFXbbsT0a6Pb+F0AmK5hrIOOwv9wvH9n2Q86j4oWNot1MAFP78ZVgAnLzbNLjv/80j6629jgL4UmMwSxuX7ZUTHyZ38B82eF8e/edRkYbzSFoqAvJxMjVoryWNpMYcoYbyLka48rqfd7lD9ZBLcQ+SCMAphqsPzgzW2upGvY0iK68typiBBiNvOKGYdYwCPSSkSGAwI4qYDZCGJuG3pjeQ5tFna5QblFVNLh9rKWlppzPjMXgmlEHOPSdBx/GmiYA1cvGf6VzxPP/8W/rlDKfGkjOZi/o1eFchiQaCyczJm7Ue4TV6XtAIbhr9GiVl4NI5YNELmTXzzxQGkp69Vw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
